name: Build Application

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up FASM
        uses: stevenwdv/setup-fasm@v1.4.1
        with:
          edition: fasm1

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: shellbin-${{ hashFiles('**/Cargo.lock') }}-deps

      - name: Build project
        run: cargo build --verbose

      - name: Run cargo clippy
        run: cargo clippy -- -W clippy::nursery -Dwarnings

      - name: Run cargo fmt
        run: cargo fmt --check
