name: Create Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  release:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up FASM
        uses: stevenwdv/setup-fasm@v1.4.1
        with:
          edition: fasm1

      - name: Add Linux Target
        run: rustup target add x86_64-unknown-linux-musl

      - name: Compile for Linux
        run: cargo build --release --target=x86_64-unknown-linux-musl

      - name: Compile for Windows
        run: cargo build --release --target=x86_64-pc-windows-msvc

      - name: Archive Binaries
        run: |
          7z a shellbin-x86_64-windows-msvc.zip .\target\x86_64-pc-windows-msvc\release\shellbin.exe
          7z a shellbin-x86_64-linux-musl.gz .\target\x86_64-unknown-linux-musl\release\shellbin

      - name: Upload Binaries
        uses: softprops/action-gh-release@v2.0.4
        with:
          files: |
            shellbin-x86_64-windows-msvc.zip
            shellbin-x86_64-linux-musl.gz
